This notebook will be used for researching and making new tables in the sqlite database that we will use

In [2]:
import sqlite3

In [9]:
conn = sqlite3.connect('inventorysystem.db')

creating the user Master data

In [6]:
conn.execute("""
create table users(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
usercode varchar(25),
name varchar(40)
)
""")

conn.execute("""
create table product(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
productcode varchar(25),
name varchar(40),
stock int
)
""")

conn.commit()
conn.close()

In [10]:
import pandas as pd

In [11]:
users = pd.read_sql("select * from users", conn)
product = pd.read_sql("select * from product", conn)

In [12]:
users

Empty DataFrame
Columns: [Id, usercode, name]
Index: []

In [13]:
product

Empty DataFrame
Columns: [Id, productcode, name, stock]
Index: []