This notebook will be used for researching and making new tables in the sqlite database that we will use

In [1]:
import sqlite3

In [2]:
conn = sqlite3.connect('inventorysystem.db')

creating the user Master data

In [6]:
conn.execute("""
create table users(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
usercode varchar(25),
name varchar(40)
)
""")

conn.execute("""
create table product(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
productcode varchar(25),
name varchar(40),
stock int
)
""")

conn.commit()
conn.close()

In [3]:
import pandas as pd

In [4]:
users = pd.read_sql("select * from users", conn)
product = pd.read_sql("select * from product", conn)

In [15]:
conn.execute('drop table users')
conn.commit()

In [19]:
conn.execute("""
CREATE TABLE users (
    Id       INTEGER PRIMARY KEY AUTOINCREMENT,
    name     TEXT NOT NULL,
    usercode TEXT GENERATED ALWAYS AS ('U-' || Id) VIRTUAL
)
""")
conn.commit()

In [30]:
conn = sqlite3.connect('inventorysystem.db')
users = pd.read_sql("select * from users", conn)
users

   Id     name usercode
0   1    Fahad      U-1
1   2    Ahmed      U-2
2   3  Bilawal      U-3
3   5    Osama      U-5
4   6   Waseem      U-6

In [6]:
product

Empty DataFrame
Columns: [Id, productcode, name, stock]
Index: []

In [7]:
dictionary = {
    'name': 'Fahad',
    'city': 'Karachi'
}

In [10]:
l = ['a','b','c']
l

['a', 'b', 'c']

In [20]:
a = ", ".join(f"{k} = ?" for k in dictionary.keys())
a

'name = ?, city = ?'

In [18]:
values = list(dictionary.values()) + [user_id]
values

['Fahad', 'Karachi', 1]

In [ ]:
# conn.execute(f"UPDATE users set {a} where Id =?",values)
# name = ?, city = ?